[workspace]
resolver = "2"
members = [
	"util/version",
	"player-color-param",
]

[workspace.dependencies]
version = { path = "util/version" }

[workspace.package]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/KojoBailey/nucc-binary-lib-rs"
