[workspace]
resolver = "2"
members = [
	"player-color-param",
]

[workspace.dependencies]
# If shared dependencies ever arise, add them here.

[workspace.package]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/KojoBailey/nucc-binary-lib-rs"
