[workspace]
resolver = "2"
members = [
	"util/version",
	"player-color-param",
	"message-info",
]

[workspace.dependencies]
indexmap = "2.0"

[workspace.package]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/KojoBailey/nucc-binary-lib-rs"
