[package]
name = "version"
version = "1.0.0"
authors = ["Kojo Bailey"]
description = "Simple version struct."
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
